linters:
  enable:
    - depguard
    - exportloopref
    - gofmt
    - gosec
    - ineffassign
    - misspell
    - nolintlint
    - revive
    - staticcheck
    - tenv
    - unconvert
    - unused
    - vet
  disable:
    - errcheck

linters-settings:
  depguard:
    list-type: denylist
    include-go-root: true
    packages:
      # use "io" or "os" instead
      # https://go.dev/doc/go1.16#ioutil
      - io/ioutil
